### ISSUE TITLE
Error while running servalcat

### ISSUE THREAD

**Issue by simonmiljan** [keitaroyam/servalcat#1]
Hi,
I've installed the latest nightly build of ccpem and when I've tried to run servalcat, I receive the following error:

[10-0-0-18:~] Miljan% which gemmi
/usr/local/bin/ccpem-20210709/bin/gemmi
[10-0-0-18:~] Miljan% which servalcat
/usr/local/bin/ccpem-20210709/bin/servalcat
[10-0-0-18:~] Miljan% servalcat
Traceback (most recent call last):
  File "/usr/local/bin/ccpem-20210709/bin/servalcat", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/bin/ccpem-20210709/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/bin/ccpem-20210709/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/bin/ccpem-20210709/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/bin/ccpem-20210709/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/bin/ccpem-20210709/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/bin/ccpem-20210709/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gemmi>=0.4.7' distribution was not found and is required by servalcat

This is a bit confusing since gemmi is present in the folder and 'reacts' to commands. Please advise how to proceed and fix this problem
Best,
Miljan

**Comment by keitaroyam** [comment]
Thanks for your interest! I guess your gemmi is old, or an old gemmi and the new one coexist. If you already installed the new gemmi, probably it should work just by removing (or renaming) old one that came with ccpem installation. I think its path is ` /usr/local/bin/ccpem-20210709/lib/py2/gemmi.so`.

**Comment by simonmiljan** [comment]
Hi,
Thanks for getting back to me so quickly! I did upgrade gemmi but I am
still receiving the same error message.
What should I do next?
Best,
Miljan

**Comment by keitaroyam** [comment]
How did you upgrade gemmi?

Can you show me the output of the following command?
```sh
/usr/local/bin/ccpem-20210709/bin/ccpem-python -c "import gemmi; print(gemmi)"
```

**Comment by simonmiljan** [comment]
It seems that I was able to resolve the issue by uninstalling, reinstalling
and updating pip. The only gemmi I have is within the ccpem folder and it
is 0.4.7:


[image: Screen Shot 2021-08-16 at 2.10.28 PM.png]
After reinstalling servalcat and renaming old version within the ccpem
folder, I was able to communicate with the program:

[image: Screen Shot 2021-08-16 at 2.12.29 PM.png]\
I will let you know if I hit any other hurdles going forward.
Best,
Miljan

**Comment by keitaroyam** [comment]
Unfortunately I cannot see your attached files, but it is good to hear that it worked. Please contact me in case you have any further troubles/questions.

**Comment by simonmiljan** [comment]
Thanks!
Best,
Miljan
